#!/usr/bin/env bash
# generate-diff-report.sh - produce the stock-vs-eNFS diff report.
#
# Usage:  generate-diff-report.sh [REMOTE:]PATH_TO_OE_KERNEL [REMOTE:]PATH_TO_UBUNTU_KERNEL
# Example:
#   scripts/generate-diff-report.sh \
#       build-host:/srv/kernel-work/openeuler/OLK-6.6 \
#       build-host:/srv/kernel-work/ubuntu/linux-7.0.0
#
# Compares each file under vendor/openeuler/ against:
#   1. its OpenEuler-stock counterpart (the original Linux source the
#      OpenEuler patches were applied to). For files newly added by
#      enfs (fs/nfs/enfs/*, *_adapter.*) there is no comparison;
#      these are flagged as "new".
#   2. its Ubuntu-stock counterpart (Ubuntu 26.04 / kernel 7.0).
#
# Both diffs together let a reader distinguish "what enfs adds" from
# "what changed between OE 6.6 and Ubuntu 7.0".
#
# Output goes to docs/differences/.

set -euo pipefail

OE="${1:?path to OpenEuler kernel checkout, possibly remote (host:path)}"
UB="${2:?path to extracted Ubuntu kernel source, possibly remote}"
HERE="$(cd "$(dirname "$0")"/.. && pwd)"
VENDOR="$HERE/vendor/openeuler"
OUT="$HERE/docs/differences"

remote_cat() {
    local target="$1"
    if [[ "$target" == *:* ]]; then
        local host="${target%%:*}" path="${target#*:}"
        ssh "$host" "cat '$path' 2>/dev/null" 2>/dev/null
    else
        cat "$target" 2>/dev/null
    fi
}

remote_exists() {
    local target="$1"
    if [[ "$target" == *:* ]]; then
        local host="${target%%:*}" path="${target#*:}"
        ssh "$host" "test -f '$path'" 2>/dev/null
    else
        test -f "$target"
    fi
}

mkdir -p "$OUT"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

declare -a FILES
mapfile -t FILES < <(cd "$VENDOR" && find . -type f \
    \( -name '*.c' -o -name '*.h' -o -name 'Kconfig' -o -name 'Makefile' \) \
    | sed 's|^\./||' | sort)

SUMMARY="$OUT/SUMMARY.md"
{
    echo "# Stock-vs-eNFS file-by-file diff summary"
    echo
    echo "Generated by \`scripts/generate-diff-report.sh\`. Two columns:"
    echo "**vs Linux 6.6** = lines added by enfs to its base kernel."
    echo "**vs Ubuntu 7.0** = total delta vs the kernel this DKMS package targets."
    echo
    echo "| File | Status | vs Ubuntu 7.0 |"
    echo "|---|---|---|"
} > "$SUMMARY"

INDEX="$OUT/README.md"
{
    cat <<'EOF'
# Stock-vs-eNFS diff report

Per-file diffs between OpenEuler's modified sources (vendored under
`vendor/openeuler/`) and:

- **OE-base** — the same file in upstream Linux 6.6, showing precisely
  what enfs adds.
- **Ubuntu 7.0** — the same file in the Ubuntu 26.04 kernel, the
  target this DKMS package builds against. This conflates "enfs adds
  X" with "Linux 6.6 → 7.0 changed Y", but it is the diff that matters
  operationally for the port.

See `SUMMARY.md` for the per-file index with line-count stats.

Files newly added by enfs (`fs/nfs/enfs/*`, the `*_adapter.*` pair,
`net/sunrpc/sunrpc_enfs_adapter.c`, `include/linux/sunrpc/sunrpc_enfs_adapter.h`)
have no upstream counterpart; their diffs against Ubuntu 7.0 are
"new file" and not interesting.

Regenerate after refreshing `vendor/openeuler/`:

```bash
scripts/generate-diff-report.sh \
    <BUILD_HOST>:/path/to/openeuler/OLK-6.6 \
    <BUILD_HOST>:/path/to/ubuntu/linux-7.0.0
```
EOF
} > "$INDEX"

for rel in "${FILES[@]}"; do
    [[ "$rel" == "UPSTREAM-REVISION" ]] && continue
    safe=$(echo "$rel" | tr '/' '-' | tr '.' '_')
    out_ub="$OUT/${safe}.vs-ubuntu.diff"

    # Local OE-modified file.
    local_file="$VENDOR/$rel"

    # Fetch counterparts.
    remote_cat "$UB/$rel" > "$TMP/ubuntu" 2>/dev/null || : > "$TMP/ubuntu"

    # Generate diffs (don't fail if they differ; that's the point).
    diff -u "$TMP/ubuntu" "$local_file" > "$out_ub" 2>/dev/null || true

    # NOTE: a "vs OE-base" diff (showing pure enfs additions, isolated
    # from 6.6→7.0 drift) requires a *vanilla* Linux 6.6 source tree as
    # an additional input. We don't have one wired in yet; if you do,
    # add a 3rd CLI argument and uncomment the block below.
    #
    # remote_cat "$OE_BASE/$rel" > "$TMP/oe" 2>/dev/null || : > "$TMP/oe"
    # diff -u "$TMP/oe" "$local_file" > "$out_oe" 2>/dev/null || true
    if [[ -s "$out_ub" ]]; then
        ub_added=$(grep -c '^+[^+]' "$out_ub" || true)
        ub_removed=$(grep -c '^-[^-]' "$out_ub" || true)
        ub_stat="+${ub_added} -${ub_removed}"
    else
        ub_stat="(identical / new file)"
    fi

    # Status: file new in OE? (no Ubuntu counterpart)
    if remote_exists "$UB/$rel"; then
        status="patched"
    else
        status="new in enfs"
        # Remove the empty vs-Ubuntu diff to keep dir clean.
        rm -f "$out_ub"
        ub_stat="—"
    fi

    echo "| \`$rel\` | $status | $ub_stat |" >> "$SUMMARY"
done

echo "[diff-report] wrote $(find "$OUT" -name '*.diff' | wc -l) diffs and SUMMARY.md to $OUT"
